volumes:
  nacos-data:
    driver: ${VOLUMES_DRIVER}
  nacos-logs:
    driver: ${VOLUMES_DRIVER}

services:

### Nacos Server ################################################
  nacos-server:
    build:
      context: ${NACOS_HOST_PATH}
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        NACOS_VERSION: ${NACOS_VERSION}
    container_name: ${NACOS_CONTAINER_NAME}
    hostname: ${NACOS_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      TZ: ${TZ}
      LANG: "C.UTF-8"
      MODE: standalone
      PREFER_HOST_MODE: hostname
      NACOS_AUTH_TOKEN: ${NACOS_AUTH_TOKEN}
      NACOS_AUTH_IDENTITY_KEY: ${NACOS_AUTH_IDENTITY_KEY}
      NACOS_AUTH_IDENTITY_VALUE: ${NACOS_AUTH_IDENTITY_VALUE}
      SPRING_DATASOURCE_PLATFORM: mysql
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-logs:/home/nacos/logs
      - "${NACOS_HOST_PATH}/application.properties:/home/nacos/conf/application.properties"
    ports:
      - "${NACOS_WEB_PORT}:8080"
      - "${NACOS_MAIN_PORT}:8848"
      - "${NACOS_GRPC_PORT}:9848"
    networks:
      backend:
        ipv4_address: ${NACOS_BACKEND_IP}
