auth_enabled: false

limits_config:
  retention_period: 720h  # 全局默认30天
  allow_structured_metadata: true
  volume_enabled: true
  ingestion_rate_mb: 30
  ingestion_burst_size_mb: 60
  per_stream_rate_limit: '5MB'
  per_stream_rate_limit_burst: '20MB'
  max_line_size: 5242880 # 5M
  max_global_streams_per_user: 15000
  
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

memberlist:
  join_members: ["${LOKI_READ_CONTAINER_NAME}", "${LOKI_WRITE_CONTAINER_NAME}", "${LOKI_BACKEND_CONTAINER_NAME}"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2025-07-01
      store: tsdb
      object_store: alibabacloud
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  alibabacloud:
    bucket: ${LOKI_ALI_OSS_BUCKET}
    endpoint: ${LOKI_ALI_OSS_ENDPOINT}
    access_key_id: ${LOKI_ALI_OSS_ACCESS_KEY_ID}
    secret_access_key: ${LOKI_ALI_OSS_ACCESS_KEY}
  localrustfs:
    s3: http://${LOKI_RUSTFS_ACCESS_KEY_ID}:${LOKI_RUSTFS_ACCESS_KEY}@${LOKI_RUSTFS_ENDPOINT}
    s3forcepathstyle: true
    
common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://${LOKI_BACKEND_CONTAINER_NAME}:3100
  ring:
    kvstore:
      store: memberlist

compactor:
  working_directory: /tmp/compactor