volumes:
  redis-data:
    driver: ${VOLUMES_DRIVER}

services:

### Redis ##############################################
  redis:
    build:
      context: ${REDIS_HOST_PATH}
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: ${REDIS_CONTAINER_NAME}
    hostname: ${REDIS_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    command: "--requirepass ${REDIS_PASSWORD} --appendonly yes"
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_HOST_PORT}:6379"
    environment:
      TZ: "${TZ}"
    networks:
      backend:
        ipv4_address: ${REDIS_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "2>/dev/null", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
