apiVersion: 1
datasources:
  - name: loki
    type: loki
    access: proxy
    url: http://nginx:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "zhiniuai"