services:

### YAPI ##############################################
  yapi:
    build:
      context: ${YAPI_HOST_PATH}
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        YAPI_VERSION: ${YAPI_VERSION}
    container_name: ${YAPI_CONTAINER_NAME}
    hostname: ${YAPI_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      TZ: ${TZ}
      YAPI_ADMIN_ACCOUNT: ${YAPI_ADMIN_ACCOUNT}
      YAPI_ADMIN_PASSWORD: ${YAPI_ADMIN_PASSWORD}
      YAPI_DB_SERVERNAME: ${YAPI_DB_SERVERNAME}
      YAPI_DB_PORT: ${YAPI_DB_PORT}
      YAPI_DB_DATABASE: ${YAPI_DB_DATABASE}
      YAPI_DB_USER: ${YAPI_DB_USER}
      YAPI_DB_PASS: ${YAPI_DB_PASS}
      YAPI_CLOSE_REGISTER: true
      YAPI_MAIL_ENABLE: false
    networks:
      backend:
        ipv4_address: ${YAPI_BACKEND_IP}
    ports:
      - ${YAPI_PORT}:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
