volumes:
  postgres-data:
    driver: ${VOLUMES_DRIVER}
  liyue-postgres-data:
    driver: ${VOLUMES_DRIVER}
  qingqiu-postgres-data:
    driver: ${VOLUMES_DRIVER}

services:

### PostgreSQL ###########################################
  postgres:
    build:
      context: ${POSTGRES_HOST_PATH}
      dockerfile: ./_context/Dockerfile
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    hostname: ${POSTGRES_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GITLAB_POSTGRES_INIT: ${GITLAB_POSTGRES_INIT}
      GITLAB_POSTGRES_USER: ${GITLAB_POSTGRES_USER}
      GITLAB_POSTGRES_PASSWORD: ${GITLAB_POSTGRES_PASSWORD}
      GITLAB_POSTGRES_DB: ${GITLAB_POSTGRES_DB}
      SONARQUBE_POSTGRES_INIT: ${SONARQUBE_POSTGRES_INIT}
      SONARQUBE_POSTGRES_DB: ${SONARQUBE_POSTGRES_DB}
      SONARQUBE_POSTGRES_USER: ${SONARQUBE_POSTGRES_USER}
      SONARQUBE_POSTGRES_PASSWORD: ${SONARQUBE_POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${POSTGRES_HOST_PATH}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      backend:
        ipv4_address: ${POSTGRES_BACKEND_IP}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

### LIYUE PostgreSQL ###########################################
  liyue-postgres:
    build:
      context: ${LIYUE_POSTGRES_HOST_PATH}
      dockerfile: ./_context/Dockerfile
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        POSTGRES_VERSION: ${LIYUE_POSTGRES_VERSION}
    container_name: ${LIYUE_POSTGRES_CONTAINER_NAME}
    hostname: ${LIYUE_POSTGRES_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${LIYUE_POSTGRES_DB}
      POSTGRES_USER: ${LIYUE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LIYUE_POSTGRES_PASSWORD}
    volumes:
      - liyue-postgres-data:/var/lib/postgresql/data
      - ${LIYUE_POSTGRES_HOST_PATH}/liyue/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${LIYUE_POSTGRES_HOST_PORT}:5432"
    networks:
      backend:
        ipv4_address: ${LIYUE_POSTGRES_BACKEND_IP}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $LIYUE_POSTGRES_USER -d $LIYUE_POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

### QINGQIU PostgreSQL ###########################################
  qingqiu-postgres:
    build:
      context: ${QINGQIU_POSTGRES_HOST_PATH}
      dockerfile: ./_context/Dockerfile
      args:
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
        POSTGRES_VERSION: ${QINGQIU_POSTGRES_VERSION}
    container_name: ${QINGQIU_POSTGRES_CONTAINER_NAME}
    hostname: ${QINGQIU_POSTGRES_HOSTNAME}
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${QINGQIU_POSTGRES_DB}
      POSTGRES_USER: ${QINGQIU_POSTGRES_USER}
      POSTGRES_PASSWORD: ${QINGQIU_POSTGRES_PASSWORD}
    volumes:
      - qingqiu-postgres-data:/var/lib/postgresql/data
      - ${QINGQIU_POSTGRES_HOST_PATH}/qingqiu/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${QINGQIU_POSTGRES_HOST_PORT}:5432"
    networks:
      backend:
        ipv4_address: ${QINGQIU_POSTGRES_BACKEND_IP}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $QINGQIU_POSTGRES_USER -d $QINGQIU_POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
      