#### yapi ####

YapiRouterAnchor: &YapiRouterAnchor
  rule: "Host(`yapi.devops.top`)"
  service: YapiSvc
  middlewares:

#### zentao ####

ZentaoRouterAnchor: &ZentaoRouterAnchor
  rule: "Host(`zentao.devops.cn`)"
  service: ZentaoSvc
  middlewares:

#### NeneData ####

NineDataRouterAnchor: &NineDataRouterAnchor
  rule: "Host(`ninedata.devops.top`)"
  service: NinedataSvc
  middlewares:

#### Http ####

http:
  services:
    YapiSvc:
      loadBalancer:
        servers:
          - url: "http://yapi:3000"
    ZentaoSvc:
      loadBalancer:
        servers:
          - url: "http://zentao:80"
    NinedataSvc:
      loadBalancer:
        servers:
          - url: "http://ninedata:9999"
    traefikWhoamiSvc:
      loadBalancer:
        servers:
          - url: "http://whoami1:80"
    traefikWhoami2Svc:
      loadBalancer:
        servers:
          - url: "http://whoami2:80"

  middlewares:
    traefikWhoamiReplacepathregex:
      replacePathRegex:
        regex: "^/api/english/(.*)"
        replacement: "/api/${1}"
    traefikWhoami2Replacepathregex:
      replacePathRegex:
        regex: "^/api/math/(.*)"
        replacement: "/api/${1}"

  routers:

    #### yapi ####

    YapiHttp:
      <<: *YapiRouterAnchor
      entryPoints:
        - web
      priority: 100

    #### zentao ####

    ZentaoHttp:
      <<: *ZentaoRouterAnchor
      entryPoints:
        - web
      priority: 100

    #### ninedata ####
    NinedataHttp:
      <<: *NineDataRouterAnchor
      entryPoints:
        - web
      priority: 100

    traefikWhoami:
      entryPoints:
        - web
      rule: "Host(`whoami1.devops.top`) && PathPrefix(`/api/english/`)"
      service: traefikWhoamiSvc
      middlewares:
        - traefikWhoamiReplacepathregex
        
    traefikWhoami2:
      entryPoints:
        - web
      rule: "Host(`whoami2.devops.top`) && PathPrefix(`/api/math/`)"
      service: traefikWhoami2Svc
      middlewares:
        - traefikWhoami2Replacepathregex
