# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /certs/devops.top/devops.top.pem
#         keyFile: /certs/devops.top/devops.top.key
        
#   certificates:
#     - certFile: /certs/devops.top/devops.top.pem
#       keyFile: /certs/devops.top/devops.top.key
#       stores:
#         - default

RedirectHttpToHttpsRouterAnchor: &RedirectHttpToHttpsRouterAnchor
  entryPoints:
    - web
  priority: 2000
  middlewares:
    - redirectToHttps
  service: noop@internal
        
http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginListRegex: 
          - "^https?://([a-zA-Z0-9-]+\\.)*devops\\.top$"
        accessControlAllowHeaders: "Dnt,Host,Pragma,Cache-Control,Ua,Time,Enduser,Address,Network,Extendid,X-Requested-With,User-Agent,Source,Devicesn,Accept,Pkgsource,Platform,Referer,Accept-Encoding,Accept-Language,Cookie,App-Id,Lcdp-Csrf-Token,Lcdp-Signature,X-CustomHeader,Keep-Alive,If-Modified-Since,Authorization,Content-Type,Devicetype,Token,Secret,Referrer-Policy"
        accessControlAllowMethods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
        accessControlAllowCredentials: true
        accessControlMaxAge: 1728000
        browserXssFilter: true
        addVaryHeader: true
        contentTypeNosniff: false

    hsts:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        forceSTSHeader: true
        contentSecurityPolicy: "default-src 'self'"
        referrerPolicy: "strict-origin-when-cross-origin"

    redirectToHttps:
      redirectScheme:
        scheme: https
        permanent: true
        port: "443"
        
  routers:
    # RedirectHttpToHttps1:
    #   <<: *RedirectHttpToHttpsRouterAnchor
    #   rule: "(HostRegexp(`^.+(-)(api)\\.devops\\.top$`) && (PathPrefix(`/api/english/`) || PathPrefix(`/english/rpc/`) || PathPrefix(`/job-api/english/`)))"
    # RedirectHttpToHttps2:
    #   <<: *RedirectHttpToHttpsRouterAnchor
    #   rule: "HostRegexp(`^.+(-)(dc|t|s|zy)\\.devops\\.top$`)"
    RedirectHttpToHttps3:
      <<: *RedirectHttpToHttpsRouterAnchor
      rule: "HostRegexp(`^(domain)\\.devops\\.top$`)"
