#### Grafana ####

GrafanaRouterAnchor: &GrafanaRouterAnchor
  rule: "Host(`grafana.devops.top`)"
  service: GrafanaSvc
  middlewares:

#### Alloy ####

AlloyRouterAnchor: &AlloyRouterAnchor
  rule: "Host(`alloy.devops.top`)"
  service: AlloySvc
  middlewares:
    - alloyUi

#### Http ####

http:
  services:
    GrafanaSvc:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
    AlloySvc:
      loadBalancer:
        servers:
          - url: "http://alloy:12345"
  middlewares:
    alloyUi:
      basicAuth:
        usersFile: /run/secrets/alloy_basicauth_users

  routers:

    #### Grafana ####

    GrafanaHttp:
      <<: *GrafanaRouterAnchor
      entryPoints:
        - web
      priority: 100

    #### Alloy ####

    AlloyHttp:
      <<: *AlloyRouterAnchor
      entryPoints:
        - web
      priority: 100
